#ifndef ROADRASH_BIKE_SHOP_STREAM_PATHS_H
#define ROADRASH_BIKE_SHOP_STREAM_PATHS_H

#define BIKE_SHOP_RAT_PERRO_STREAM_PATH_SIZE 44
#define BIKE_SHOP_RAT_CORSAIR_STREAM_PATH_SIZE 48
#define BIKE_SHOP_RAT_BANZAI_STREAM_PATH_SIZE 44
#define BIKE_SHOP_RAT_KILLER_STREAM_PATH_SIZE 44
#define BIKE_SHOP_RAT_KAMAKAZI_STREAM_PATH_SIZE 48
#define BIKE_SHOP_SPORT_STILETTO_STREAM_PATH_SIZE 52
#define BIKE_SHOP_SPORT_DIABLO_STREAM_PATH_SIZE 48
#define BIKE_SHOP_SPORT_PERRO_STREAM_PATH_SIZE 48
#define BIKE_SHOP_SPORT_DMG_STREAM_PATH_SIZE 48
#define BIKE_SHOP_SPORT_KAMAKAZI_STREAM_PATH_SIZE 52
#define BIKE_SHOP_SUPER_STILETTO_STREAM_PATH_SIZE 52
#define BIKE_SHOP_SUPER_DIABLO_STREAM_PATH_SIZE 48
#define BIKE_SHOP_SUPER_CORSAIR_STREAM_PATH_SIZE 52
#define BIKE_SHOP_SUPER_BANZAI_STREAM_PATH_SIZE 48
#define BIKE_SHOP_SUPER_KAMAKAZI_STREAM_PATH_SIZE 52

extern const unsigned char
  bike_shop_rat_perro_stream_path[BIKE_SHOP_RAT_PERRO_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_rat_corsair_stream_path[BIKE_SHOP_RAT_CORSAIR_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_rat_banzai_stream_path[BIKE_SHOP_RAT_BANZAI_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_rat_killer_stream_path[BIKE_SHOP_RAT_KILLER_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_rat_kamakazi_stream_path[BIKE_SHOP_RAT_KAMAKAZI_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_sport_stiletto_stream_path[BIKE_SHOP_SPORT_STILETTO_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_sport_diablo_stream_path[BIKE_SHOP_SPORT_DIABLO_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_sport_perro_stream_path[BIKE_SHOP_SPORT_PERRO_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_sport_dmg_stream_path[BIKE_SHOP_SPORT_DMG_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_sport_kamakazi_stream_path[BIKE_SHOP_SPORT_KAMAKAZI_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_super_stiletto_stream_path[BIKE_SHOP_SUPER_STILETTO_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_super_diablo_stream_path[BIKE_SHOP_SUPER_DIABLO_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_super_corsair_stream_path[BIKE_SHOP_SUPER_CORSAIR_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_super_banzai_stream_path[BIKE_SHOP_SUPER_BANZAI_STREAM_PATH_SIZE];
extern const unsigned char
  bike_shop_super_kamakazi_stream_path[BIKE_SHOP_SUPER_KAMAKAZI_STREAM_PATH_SIZE];

#endif
