#ifndef FRONT_END_COMMANDS_H
#define FRONT_END_COMMANDS_H

#define FRONT_END_SELECTION_MASK 0xFF

typedef enum FrontEndGameMode
{
  FRONT_END_GAME_MODE_STANDARD = 0,
  FRONT_END_GAME_MODE_ALTERNATE = 1
} FrontEndGameMode;

typedef enum FrontEndPlayerCount
{
  FRONT_END_SINGLE_PLAYER = 1,
  FRONT_END_TWO_PLAYERS = 2
} FrontEndPlayerCount;

typedef enum ProfileSlot
{
  PROFILE_SLOT_ONE = 0,
  PROFILE_SLOT_TWO = 1,
  PROFILE_SLOT_THREE = 2,
  PROFILE_SLOT_FOUR = 3,
  PROFILE_SLOT_FIVE = 4,
  PROFILE_SLOT_SIX = 5,
  PROFILE_SLOT_SEVEN = 6,
  PROFILE_SLOT_EXIT = 7
} ProfileSlot;

typedef enum RiderTypeId
{
  RIDER_TYPE_PLAYER_ONE = 0,
  RIDER_TYPE_MIKE = 1,
  RIDER_TYPE_CYDNEY = 2,
  RIDER_TYPE_JIM = 3,
  RIDER_TYPE_PEARL = 4,
  RIDER_TYPE_JON = 5,
  RIDER_TYPE_RHONDA = 6,
  RIDER_TYPE_BOSE = 7,
  RIDER_TYPE_AXLE = 8,
  RIDER_TYPE_PLAYER_TWO = 9
} RiderTypeId;

typedef enum RiderStyleId
{
  RIDER_STYLE_SPORT_450 = 0,
  RIDER_STYLE_SWALLOW = 1,
  RIDER_STYLE_ZYX_250 = 2,
  RIDER_STYLE_KILLER = 3,
  RIDER_STYLE_PICO = 4,
  RIDER_STYLE_711_SS1 = 5,
  RIDER_STYLE_RAVEN_N = 6,
  RIDER_STYLE_VIPERA_N = 7,
  RIDER_STYLE_ZYX_750N = 8,
  RIDER_STYLE_ASSASSINO = 9,
  RIDER_STYLE_VAMPIRO = 10,
  RIDER_STYLE_M10 = 11,
  RIDER_STYLE_ZYX_750 = 12,
  RIDER_STYLE_GRANDE = 13,
  RIDER_STYLE_AGGRESSORE = 14
} RiderStyleId;

typedef enum RiderVariantId
{
  RIDER_VARIANT_PRIMARY = 0,
  RIDER_VARIANT_ONE = 1,
  RIDER_VARIANT_TWO = 2,
  RIDER_VARIANT_THREE = 3,
  RIDER_VARIANT_FOUR = 4,
  RIDER_VARIANT_COUNT = 5
} RiderVariantId;

typedef enum FrontEndMenuId
{
  FRONT_END_MENU_PROFILE_GROUP_A = 0xAD,
  FRONT_END_MENU_PROFILE_GROUP_B = 0xC0,
  FRONT_END_MENU_PROFILE_GROUP_C = 0xD1,
  FRONT_END_MENU_DEFAULT_RIDER_SETUP = 0xE2,
  FRONT_END_MENU_DEFAULT_VARIANT = 0xEB,
  FRONT_END_MENU_ALTERNATE_RIDER_SETUP = 0xF2,
  FRONT_END_MENU_RIDER_SETUP_COMPLETE = 0x1E2,
  FRONT_END_MENU_EXIT_APPLICATION = 0x1F3,
  FRONT_END_MENU_FINISH_SESSION = 0x1F4
} FrontEndMenuId;

typedef enum FrontEndCommandId
{
  FRONT_END_COMMAND_SET_STANDARD_MODE_A = 0x07,
  FRONT_END_COMMAND_SET_ALTERNATE_MODE_A = 0x08,
  FRONT_END_COMMAND_SHOW_ALTERNATE_SETUP = 0x09,
  FRONT_END_COMMAND_SCAN_LOAD_SLOTS_A = 0x0B,
  FRONT_END_COMMAND_COPY_MENU_OVERRIDE_A = 0x12,
  FRONT_END_COMMAND_SET_ALTERNATE_MODE_B = 0x14,
  FRONT_END_COMMAND_SET_STANDARD_MODE_B = 0x15,
  FRONT_END_COMMAND_SET_SINGLE_PLAYER_A = 0x17,
  FRONT_END_COMMAND_SET_TWO_PLAYERS_A = 0x18,
  FRONT_END_COMMAND_ENABLE_ENGINE_AUDIO_A = 0x21,
  FRONT_END_COMMAND_DISABLE_ENGINE_AUDIO_A = 0x22,
  FRONT_END_COMMAND_ENABLE_MUSIC_A = 0x26,
  FRONT_END_COMMAND_DISABLE_MUSIC_A = 0x27,
  FRONT_END_COMMAND_SCAN_LOAD_SLOTS_B = 0x2B,
  FRONT_END_COMMAND_SCAN_SAVE_SLOTS = 0x2C,
  FRONT_END_COMMAND_COPY_MENU_OVERRIDE_B = 0x33,
  FRONT_END_COMMAND_SET_ALTERNATE_MODE_C = 0x35,
  FRONT_END_COMMAND_SET_STANDARD_MODE_C = 0x36,
  FRONT_END_COMMAND_SET_SINGLE_PLAYER_B = 0x38,
  FRONT_END_COMMAND_SET_TWO_PLAYERS_B = 0x39,
  FRONT_END_COMMAND_ENABLE_ENGINE_AUDIO_B = 0x42,
  FRONT_END_COMMAND_DISABLE_ENGINE_AUDIO_B = 0x43,
  FRONT_END_COMMAND_ENABLE_MUSIC_B = 0x47,
  FRONT_END_COMMAND_DISABLE_MUSIC_B = 0x48,
  FRONT_END_COMMAND_SCAN_LOAD_SLOTS_C = 0x4C,
  FRONT_END_COMMAND_COPY_MENU_OVERRIDE_C = 0x53,
  FRONT_END_COMMAND_SET_ALTERNATE_MODE_D = 0x55,
  FRONT_END_COMMAND_SET_STANDARD_MODE_D = 0x56,
  FRONT_END_COMMAND_SET_SINGLE_PLAYER_C = 0x58,
  FRONT_END_COMMAND_SET_TWO_PLAYERS_C = 0x59,
  FRONT_END_COMMAND_ENABLE_ENGINE_AUDIO_C = 0x62,
  FRONT_END_COMMAND_DISABLE_ENGINE_AUDIO_C = 0x63,
  FRONT_END_COMMAND_ENABLE_MUSIC_C = 0x67,
  FRONT_END_COMMAND_DISABLE_MUSIC_C = 0x68,
  FRONT_END_COMMAND_PROFILE_GROUP_A_FIRST = 0xAE,
  FRONT_END_COMMAND_PROFILE_GROUP_B_FIRST = 0xC1,
  FRONT_END_COMMAND_PROFILE_GROUP_C_FIRST = 0xD2,
  FRONT_END_COMMAND_SELECT_RIDER_FIRST = 0xE3,
  FRONT_END_COMMAND_SELECT_VARIANT_A_FIRST = 0xEC,
  FRONT_END_COMMAND_SELECT_VARIANT_B_FIRST = 0xF3,
  FRONT_END_COMMAND_SHOW_ALTERNATE_SETUP_AGAIN = 0xF8,
  FRONT_END_COMMAND_SELECT_STYLE_PICO = 0x10D,
  FRONT_END_COMMAND_SELECT_STYLE_SPORT_450 = 0x11A,
  FRONT_END_COMMAND_SELECT_STYLE_SWALLOW = 0x127,
  FRONT_END_COMMAND_SELECT_STYLE_KILLER = 0x134,
  FRONT_END_COMMAND_SELECT_STYLE_ZYX_250 = 0x141,
  FRONT_END_COMMAND_SELECT_STYLE_AGGRESSORE = 0x155,
  FRONT_END_COMMAND_SELECT_STYLE_VAMPIRO = 0x162,
  FRONT_END_COMMAND_SELECT_STYLE_GRANDE = 0x16F,
  FRONT_END_COMMAND_SELECT_STYLE_M10 = 0x17C,
  FRONT_END_COMMAND_SELECT_STYLE_ZYX_750 = 0x189,
  FRONT_END_COMMAND_SELECT_STYLE_ASSASSINO = 0x19D,
  FRONT_END_COMMAND_SELECT_STYLE_VIPERA_N = 0x1AA,
  FRONT_END_COMMAND_SELECT_STYLE_RAVEN_N = 0x1B7,
  FRONT_END_COMMAND_SELECT_STYLE_711_SS1 = 0x1C4,
  FRONT_END_COMMAND_SELECT_STYLE_ZYX_750N = 0x1D1,
  FRONT_END_COMMAND_COMPLETE_RIDER_SETUP = 0x1E3
} FrontEndCommandId;

#endif
