#ifndef FRONT_END_TRANSITION_RUNTIME_H
#define FRONT_END_TRANSITION_RUNTIME_H

#include "rw_semantic_data.h"

enum
{
  FRONT_END_RIDER_DESCRIPTOR_INDEX = 2,
  FRONT_END_RIDER_MIKE_RESOURCE_OFFSET = 4,
  FRONT_END_RIDER_CYDNEY_RESOURCE_OFFSET = 2,
  FRONT_END_RIDER_JIM_RESOURCE_OFFSET = 7,
  FRONT_END_RIDER_PEARL_RESOURCE_OFFSET = 5,
  FRONT_END_RIDER_JON_RESOURCE_OFFSET = 3,
  FRONT_END_RIDER_RHONDA_RESOURCE_OFFSET = 6,
  FRONT_END_RIDER_BOSE_RESOURCE_OFFSET = 1,
  FRONT_END_RIDER_AXLE_RESOURCE_OFFSET = 0,
  FRONT_END_RIDER_MODE_FOUR_BASE_RESOURCE = 0x38A,
  FRONT_END_RIDER_MODE_FIVE_BASE_RESOURCE = 0x39B,
  FRONT_END_TRANSITION_EXIT_FRAMES = 60,
  FRONT_END_TRANSITION_INPUT_PAD = 1
};

FrontEndCelDescriptor *
select_front_end_rider_resource(FrontEndCelDescriptor *descriptors,
                                int                    base_resource_id);
int
front_end_play_transition(void);

#endif
