#include "road_procedural_curve.h"

enum RoadProceduralCurveProfileIndex
{
  ROAD_CURVE_LOW_VARIANCE_NEAR = 0,
  ROAD_CURVE_LOW_VARIANCE_MIDDLE = 1,
  ROAD_CURVE_LOW_VARIANCE_FAR = 2,
  ROAD_CURVE_HIGH_VARIANCE_NEAR = 3,
  ROAD_CURVE_HIGH_VARIANCE_MIDDLE = 4,
  ROAD_CURVE_HIGH_VARIANCE_FAR = 5
};

enum RoadProceduralCurveProfileValue
{
  ROAD_CURVE_LOW_NEAR_LATERAL_MINIMUM = -80,
  ROAD_CURVE_LOW_NEAR_LATERAL_MAXIMUM = 180,
  ROAD_CURVE_LOW_OTHER_LATERAL_MINIMUM = -20,
  ROAD_CURVE_LOW_OTHER_LATERAL_MAXIMUM = 400,
  ROAD_CURVE_HIGH_NEAR_LATERAL_MINIMUM = -80,
  ROAD_CURVE_HIGH_NEAR_LATERAL_MAXIMUM = 384,
  ROAD_CURVE_HIGH_OTHER_LATERAL_MINIMUM = -20,
  ROAD_CURVE_HIGH_OTHER_LATERAL_MAXIMUM = 512,
  ROAD_CURVE_NEAR_LONGITUDINAL_MINIMUM = 750,
  ROAD_CURVE_NEAR_LONGITUDINAL_MAXIMUM = 1250,
  ROAD_CURVE_LOW_MIDDLE_LONGITUDINAL_MINIMUM = 2000,
  ROAD_CURVE_LOW_MIDDLE_LONGITUDINAL_MAXIMUM = 2500,
  ROAD_CURVE_LOW_FAR_LONGITUDINAL_MINIMUM = 3250,
  ROAD_CURVE_LOW_FAR_LONGITUDINAL_MAXIMUM = 3750,
  ROAD_CURVE_HIGH_MIDDLE_LONGITUDINAL_MINIMUM = 1750,
  ROAD_CURVE_HIGH_MIDDLE_LONGITUDINAL_MAXIMUM = 2250,
  ROAD_CURVE_HIGH_FAR_LONGITUDINAL_MINIMUM = 3000,
  ROAD_CURVE_HIGH_FAR_LONGITUDINAL_MAXIMUM = 3500,
  ROAD_CURVE_LATERAL_DELTA_LIMIT = 128,
  ROAD_CURVE_LONGITUDINAL_DELTA_LIMIT = 256,
  ROAD_CURVE_SHORT_RUN_MINIMUM = 2,
  ROAD_CURVE_SHORT_RUN_MAXIMUM = 5,
  ROAD_CURVE_STANDARD_RUN_MINIMUM = 3,
  ROAD_CURVE_STANDARD_RUN_MAXIMUM = 10,
  ROAD_CURVE_MODERATE_RUN_MINIMUM = 3,
  ROAD_CURVE_MODERATE_RUN_MAXIMUM = 7
};

static RoadProceduralCurveProfile *const
procedural_road_curve_profiles_reference =
  gRoadProceduralCurveProfiles;

void
initialize_procedural_road_curve_profiles(void)
{
  RoadProceduralCurveProfile *profiles;

  profiles = procedural_road_curve_profiles_reference;
  generate_random_road_curve_component(
    ROAD_PROCEDURAL_POINT_COUNT,
    ROAD_CURVE_LOW_NEAR_LATERAL_MINIMUM,
    ROAD_CURVE_LOW_NEAR_LATERAL_MAXIMUM,
    ROAD_CURVE_LATERAL_DELTA_LIMIT,
    ROAD_CURVE_SHORT_RUN_MINIMUM,
    ROAD_CURVE_SHORT_RUN_MAXIMUM,
    &profiles[ROAD_CURVE_LOW_VARIANCE_NEAR]
    .points[0].lateral_value);
  generate_random_road_curve_component(
    ROAD_PROCEDURAL_POINT_COUNT,
    ROAD_CURVE_LOW_OTHER_LATERAL_MINIMUM,
    ROAD_CURVE_LOW_OTHER_LATERAL_MAXIMUM,
    ROAD_CURVE_LATERAL_DELTA_LIMIT,
    ROAD_CURVE_STANDARD_RUN_MINIMUM,
    ROAD_CURVE_STANDARD_RUN_MAXIMUM,
    &profiles[ROAD_CURVE_LOW_VARIANCE_MIDDLE]
    .points[0].lateral_value);
  generate_random_road_curve_component(
    ROAD_PROCEDURAL_POINT_COUNT,
    ROAD_CURVE_LOW_OTHER_LATERAL_MINIMUM,
    ROAD_CURVE_LOW_OTHER_LATERAL_MAXIMUM,
    ROAD_CURVE_LATERAL_DELTA_LIMIT,
    ROAD_CURVE_STANDARD_RUN_MINIMUM,
    ROAD_CURVE_STANDARD_RUN_MAXIMUM,
    &profiles[ROAD_CURVE_LOW_VARIANCE_FAR]
    .points[0].lateral_value);

  generate_random_road_curve_component(
    ROAD_PROCEDURAL_POINT_COUNT,
    ROAD_CURVE_NEAR_LONGITUDINAL_MINIMUM,
    ROAD_CURVE_NEAR_LONGITUDINAL_MAXIMUM,
    ROAD_CURVE_LONGITUDINAL_DELTA_LIMIT,
    ROAD_CURVE_MODERATE_RUN_MINIMUM,
    ROAD_CURVE_MODERATE_RUN_MAXIMUM,
    &profiles[ROAD_CURVE_LOW_VARIANCE_NEAR]
    .points[0].longitudinal_value);
  generate_random_road_curve_component(
    ROAD_PROCEDURAL_POINT_COUNT,
    ROAD_CURVE_LOW_MIDDLE_LONGITUDINAL_MINIMUM,
    ROAD_CURVE_LOW_MIDDLE_LONGITUDINAL_MAXIMUM,
    ROAD_CURVE_LONGITUDINAL_DELTA_LIMIT,
    ROAD_CURVE_MODERATE_RUN_MINIMUM,
    ROAD_CURVE_MODERATE_RUN_MAXIMUM,
    &profiles[ROAD_CURVE_LOW_VARIANCE_MIDDLE]
    .points[0].longitudinal_value);
  generate_random_road_curve_component(
    ROAD_PROCEDURAL_POINT_COUNT,
    ROAD_CURVE_LOW_FAR_LONGITUDINAL_MINIMUM,
    ROAD_CURVE_LOW_FAR_LONGITUDINAL_MAXIMUM,
    ROAD_CURVE_LONGITUDINAL_DELTA_LIMIT,
    ROAD_CURVE_MODERATE_RUN_MINIMUM,
    ROAD_CURVE_MODERATE_RUN_MAXIMUM,
    &profiles[ROAD_CURVE_LOW_VARIANCE_FAR]
    .points[0].longitudinal_value);
  generate_random_road_curve_component(
    ROAD_PROCEDURAL_POINT_COUNT,
    ROAD_CURVE_HIGH_NEAR_LATERAL_MINIMUM,
    ROAD_CURVE_HIGH_NEAR_LATERAL_MAXIMUM,
    ROAD_CURVE_LATERAL_DELTA_LIMIT,
    ROAD_CURVE_MODERATE_RUN_MINIMUM,
    ROAD_CURVE_MODERATE_RUN_MAXIMUM,
    &profiles[ROAD_CURVE_HIGH_VARIANCE_NEAR]
    .points[0].lateral_value);
  generate_random_road_curve_component(
    ROAD_PROCEDURAL_POINT_COUNT,
    ROAD_CURVE_HIGH_OTHER_LATERAL_MINIMUM,
    ROAD_CURVE_HIGH_OTHER_LATERAL_MAXIMUM,
    ROAD_CURVE_LATERAL_DELTA_LIMIT,
    ROAD_CURVE_STANDARD_RUN_MINIMUM,
    ROAD_CURVE_STANDARD_RUN_MAXIMUM,
    &profiles[ROAD_CURVE_HIGH_VARIANCE_MIDDLE]
    .points[0].lateral_value);
  generate_random_road_curve_component(
    ROAD_PROCEDURAL_POINT_COUNT,
    ROAD_CURVE_HIGH_OTHER_LATERAL_MINIMUM,
    ROAD_CURVE_HIGH_OTHER_LATERAL_MAXIMUM,
    ROAD_CURVE_LATERAL_DELTA_LIMIT,
    ROAD_CURVE_STANDARD_RUN_MINIMUM,
    ROAD_CURVE_STANDARD_RUN_MAXIMUM,
    &profiles[ROAD_CURVE_HIGH_VARIANCE_FAR]
    .points[0].lateral_value);
  generate_random_road_curve_component(
    ROAD_PROCEDURAL_POINT_COUNT,
    ROAD_CURVE_NEAR_LONGITUDINAL_MINIMUM,
    ROAD_CURVE_NEAR_LONGITUDINAL_MAXIMUM,
    ROAD_CURVE_LONGITUDINAL_DELTA_LIMIT,
    ROAD_CURVE_MODERATE_RUN_MINIMUM,
    ROAD_CURVE_MODERATE_RUN_MAXIMUM,
    &profiles[ROAD_CURVE_HIGH_VARIANCE_NEAR]
    .points[0].longitudinal_value);
  generate_random_road_curve_component(
    ROAD_PROCEDURAL_POINT_COUNT,
    ROAD_CURVE_HIGH_MIDDLE_LONGITUDINAL_MINIMUM,
    ROAD_CURVE_HIGH_MIDDLE_LONGITUDINAL_MAXIMUM,
    ROAD_CURVE_LONGITUDINAL_DELTA_LIMIT,
    ROAD_CURVE_MODERATE_RUN_MINIMUM,
    ROAD_CURVE_MODERATE_RUN_MAXIMUM,
    &profiles[ROAD_CURVE_HIGH_VARIANCE_MIDDLE]
    .points[0].longitudinal_value);
  generate_random_road_curve_component(
    ROAD_PROCEDURAL_POINT_COUNT,
    ROAD_CURVE_HIGH_FAR_LONGITUDINAL_MINIMUM,
    ROAD_CURVE_HIGH_FAR_LONGITUDINAL_MAXIMUM,
    ROAD_CURVE_LONGITUDINAL_DELTA_LIMIT,
    ROAD_CURVE_MODERATE_RUN_MINIMUM,
    ROAD_CURVE_MODERATE_RUN_MAXIMUM,
    &profiles[ROAD_CURVE_HIGH_VARIANCE_FAR]
    .points[0].longitudinal_value);
}
